services:
  postgres:
    image: postgres:16-alpine
    container_name: fitmanager_postgres
    restart: always
    environment:
      POSTGRES_DB: fitmanager_db
      POSTGRES_USER: fitmanager
      POSTGRES_PASSWORD: fitmanager_pwd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitmanager -d fitmanager_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
